config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from pages.urls import pages_patterns

urlpatterns = [
    path('', include('core.urls')),
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("social.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('pages/', include(pages_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

core/urls.py
from django.urls import path
from core.views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample', SamplePageView.as_view(), name="sample"),
]

pages/urls.py
from django.urls import path
from pages.views import PageListView, PageDetailView, PageCreateView, PageDeleteView, PageUpdateView

pages_patterns = ([
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:slug>/', PageDetailView.as_view(), name="page"),
    path('create/', PageCreateView.as_view(), name="create"),
    path('delete/<int:pk>/', PageDeleteView.as_view(), name="delete"),
    path('update/<int:pk>/', PageUpdateView.as_view(), name="update"),
], 'pages')

social/users/urls.py
from django.urls import path

from social.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

core/models.py
from django.db import models

pages/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from ckeditor import fields

class Page(models.Model):
    title = models.CharField(max_length=200, verbose_name="título")
    content = fields.RichTextField(verbose_name="contenido")
    ordering = models.SmallIntegerField(default=0, verbose_name="orden")
    created = models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="fecha de actualización")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['ordering', 'title']

    def __str__(self):
        return self.title

    def get_slug(self):
        return slugify(self.title)

    def get_absolute_url(self):
        return reverse('pages:page', kwargs={'pk': self.id, 'slug': self.get_slug()})

social/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for social."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

pages/forms.py
from django import forms
from .models import Page

class PageForm(forms.ModelForm):
    
    class Meta:
        model = Page
        fields = ('title', 'content', 'ordering')
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'ordering': forms.NumberInput(attrs={'class':'form-control'}),
        }

social/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

core/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render

class HomePageView(TemplateView):
    template_name = "core/home.html"
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': "Social"})

class SamplePageView(TemplateView):
    template_name = "core/sample.html"

pages/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Page
from .forms import PageForm

class PageListView(ListView):
    model = Page

class PageDetailView(DetailView):
    model = Page

class PageCreateView(CreateView):
    model = Page
    form_class = PageForm
    #fields = ['title', 'content', 'ordering']
    success_url = reverse_lazy('pages:pages')

class PageDeleteView(DeleteView):
    model = Page
    success_url = reverse_lazy('pages:pages')

class PageUpdateView(UpdateView):
    model = Page
    form_class = PageForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return self.object.get_absolute_url() + '?ok'

social/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %} | Social</title>
        <!-- Fuentes -->
        <link href="{% static 'favicon.ico' %}" rel="shortcut icon" type="image/png">
        <link href="{% static 'core/vendor/font-awesome/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Mulish:400,400i,700,700i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
        <!-- Estilos -->
        <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- Navegación -->
        {% include 'core/includes/navbar.html' %}
        <!-- Contenido -->
        {% block content %}{% endblock %}
        <!-- Footer -->
        {% include 'core/includes/footer.html' %}
        <!-- Javascript -->
        <script src="{% static 'core/vendor/jquery/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'core/js/main.js' %}"></script>
    </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}

{% block content %}
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h1 class="page-title mb-4" style="font-size:38px;">{{ title }}</h1>
                <div>
                    <ul>
                        <li>CBV</li>
                        <li>autenticación</li>
                        <li>registros</li>
                        <li>perfiles</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

core/templates/core/includes/footer.html
<footer class="footer py-5 bg-transparent text-center">
    <div class="container">
        <p class="m-0">
            Copyright &copy; Social Site {% now 'Y' %}
        </p>
    </div>
</footer>

core/templates/core/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-transparent mb-5 pt-5" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Social</i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sample' %}">Prueba</a>
                <!--<a class="nav-link" href="{% url 'pages:pages' %}">Páginas</a>-->
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">
                        {% if request.user.is_staff %}Admin{% else %}Acceder{% endif %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav> 

core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Prueba{% endblock %}

{% block content %}
<main class="page-main" role="main">
    <div class="container">
        <div class="row justify-content-md-center mx-auto">
            <div class="col-md-3">
                <img src="{% static 'core/img/sample.jpeg' %}" class="img-fluid rounded"/>
            </div>
            <div class="col-md-6 mt-4">
                <h3 class="page-title text-left">Página de prueba</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
                Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
                Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

pages/templates/pages/includes/page_menu.html
{% load static %}
<script src="{% static 'ckeditor/ckeditor-init.js' %}" type="text/javascript" ></script>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}" type="text/javascript"></script>

{% if request.user.is_staff %}
<nav class="nav navbar-light bg-transparent justify-content-center pb-2">
    <a class="navbar-brand" href="#">
        <i class="fas fa-cogs fa-lg"></i>
    </a>
    <a class="nav-link" href="{% url 'pages:create' %}">Crear página</a>
    <a class="nav-link" href="{% url 'pages:pages' %}">Listar página</a>
</nav>
{% endif %}

pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Eliminar página{% endblock %}

{% block content %}
{% include 'pages/includes/page_menu.html'%}
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto"> 
                <h3 class="page-title text-left mb-4">Confirmar</h3>
                <div class="card py-5">
                    <form method="post">
                        {% csrf_token %}
                        <p class="text-center">¿Está seguro que quiere eliminar 
                        <strong style="color: #ee13b2;">{{ object }}</strong>?</p>
                        <p class="text-center">
                            <input type="submit" class="btn btn-outline-dark mt-4" value="Sí, eliminar la página">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

pages/templates/pages/page_detail.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}{{ page.title }}{% endblock %}

{% block content %}
{% include 'pages/includes/page_menu.html' %}
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                {% if 'ok' in request.GET %}
                <div class="alert alert-light alert-dismissible fade show" role="alert">
                    <strong>{{object}}</strong> se editó con éxito.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <h3 class="mb-4">{{ page.title }}</h3>
                <div>
                    <p>{{ page.content|safe }}</p>
                    {% if request.user.is_staff %}
                        <p><a href="{% url 'pages:update' page.id %}">
                            <span><strong>Editar</strong></span></a>
                        |<a href="{% url 'pages:delete' page.id %}">
                            <span><strong>Eliminar</strong></span></a>
                        </p> 
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

pages/templates/pages/page_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}

{% block content %}
{% include 'pages/includes/page_menu.html'%}
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-dark btn-block">
                            Publicar</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

pages/templates/pages/page_list.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}{{ page.title }}{% endblock %}

{% block content %}
{% include 'pages/includes/page_menu.html' %}
{% for page in object_list %} <!-- page_list -->
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h3 class="mb-4">{{ page.title }}</h3>
                <div class="page-content">
                    <p>{{ page.content|striptags|safe|truncatechars:200 }}</p>
                    <p><a href="{{ page.get_absolute_url }}">
                        <span><strong>Leer más</strong></span></a>
                    {% if request.user.is_staff %}
                        |<a href="{% url 'pages:update' page.id %}">
                            <span><strong>Editar</strong></span></a>
                        |<a href="{% url 'pages:delete' page.id %}">
                            <span><strong>Eliminar</strong></span></a>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</main>
{% endfor %}
{% endblock %}

pages/templates/pages/page_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Editar página{% endblock %}

{% block content %}
{% include 'pages/includes/page_menu.html'%}
<main class="page-main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-dark btn-block">
                            Editar</button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

social/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}social{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Just a unsociable girl, standing in front of a social network project, asking it to love her.">
    <meta name="author" content="Natalia">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">social</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

social/templates/pages/about.html
{% extends "base.html" %}

social/templates/pages/home.html
{% extends "base.html" %}

social/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

social/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}